services:
  postgres_test:
    image: postgres:17
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  test_app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - postgres_test
    environment:
      - DB_TEST_HOST=postgres_test
      - DB_TEST_USER=test
      - DB_TEST_PASSWORD=test
      - DB_TEST_NAME=test_db
      - DB_TEST_PORT=5432
    volumes:
      - .:/app
