services:
  postgres_test:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${DB_TEST_NAME},${DB_TEST_NAME}2,${DB_TEST_NAME}3,${DB_TEST_NAME}4,${DB_TEST_NAME}5,${DB_TEST_NAME}6,${DB_TEST_NAME}7,${DB_TEST_NAME}8
      # Performance settings for tests
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    command: >
      postgres
      -c shared_buffers=512MB
      -c work_mem=64MB
      -c maintenance_work_mem=256MB
      -c effective_cache_size=1GB
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c max_connections=200
      -c checkpoint_completion_target=0.9
      -c max_parallel_workers_per_gather=0
      -c max_parallel_workers=0
      -c autovacuum=off
      -c track_functions=none
      -c track_counts=off
    tmpfs:
      - /var/lib/postgresql/data:rw,size=2g
    network_mode: host
    volumes:
      - ./docker-entrypoint-initdb.d-create-test-dbs.sh:/docker-entrypoint-initdb.d/01-create-dbs.sh:ro
